/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	darkMode: 'class',
	theme: {
		extend: {
			fontFamily: {
				sans: ['Arial', 'system-ui', 'sans-serif'],
				mono: ['JetBrains Mono', 'monospace'],
			},
			
			spacing: {
				header: '80px',
				footer: '130px',
			},

			colors: {
				background: 'var(--color-background)',
				surface: 'var(--color-surface)',
				text: 'var(--color-text)',
				border: 'var(--color-border)',
				link: 'var(--color-link)',
				tag: 'var(--color-tag)',
				shadow: 'var(--color-shadow)',
				blue: 'var(--color-blue)',
				green: 'var(--color-green)',
				yellow: 'var(--color-yellow)',
				purple: 'var(--color-purple)',
				red: 'var(--color-red)',
			},

			/* Centralized typography overrides for @tailwindcss/typography plugin */
			typography: ({ theme }) => ({
				DEFAULT: {
					css: {
						color: 'var(--text-main)',
						maxWidth: 'none',
						fontSize: theme('fontSize.base')[0],
						lineHeight: theme('fontSize.base')[1].lineHeight,
						'--tw-prose-body': 'var(--text-main)',
						'--tw-prose-headings': 'var(--text-main)',
						'--tw-prose-lead': 'var(--text-main)',
						'--tw-prose-links': 'var(--color-link)',
						'--tw-prose-bold': 'var(--text-main)',
						'--tw-prose-counters': 'var(--text-muted)',
						'--tw-prose-bullets': 'var(--text-muted)',
						'--tw-prose-hr': 'var(--color-border)',
						'--tw-prose-quotes': 'var(--text-muted)',
						'--tw-prose-quote-borders': 'var(--color-border)',
						'--tw-prose-captions': 'var(--text-muted)',
						'--tw-prose-code': 'var(--text-main)',
						'--tw-prose-pre-code': 'var(--text-main)',
						'--tw-prose-pre-bg': 'var(--color-surface)',
						'--tw-prose-th-borders': 'var(--color-border)',
						'--tw-prose-td-borders': 'var(--color-border)',
						a: {
							color: 'var(--color-link)',
							textDecoration: 'underline',
							textUnderlineOffset: '4px',
							'&:hover': { color: 'var(--color-link)' },
						},
						h1: {
							color: 'var(--text-main)',
							fontWeight: theme('fontWeight.bold'),
							fontSize: '2.3rem',
							scrollMarginTop: theme('spacing.header'),
							paddingBottom: theme('spacing.3'),
							marginTop: theme('spacing.6'),
							marginBottom: theme('spacing.3'),
							borderBottomWidth: '1px',
							borderBottomColor: 'var(--color-border)',
						},
						h2: {
							color: 'var(--text-main)',
							fontWeight: theme('fontWeight.bold'),
							fontSize: '2rem',
							paddingBottom: theme('spacing.3'),
							marginTop: theme('spacing.6'),
							marginBottom: theme('spacing.3'),
							borderBottomWidth: '1px',
							borderBottomColor: 'var(--color-border)',
						},
						h3: {
							color: 'var(--text-main)',
							fontWeight: theme('fontWeight.bold'),
							fontSize: '1.6rem',
							marginTop: theme('spacing.6'),
							marginBottom: theme('spacing.3'),
						},
						h4: {
							color: 'var(--text-main)',
							fontWeight: theme('fontWeight.bold'),
							fontSize: '1.3rem',
							marginTop: theme('spacing.6'),
							marginBottom: theme('spacing.3'),
						},
						p: {
							color: 'var(--text-main)',
							fontSize: theme('fontSize.base')[0],
							lineHeight: theme('lineHeight.relaxed'),
							marginTop: theme('spacing.3'),
							marginBottom: theme('spacing.3'),
							textAlign: 'justify',
							'@screen lg': {
								fontSize: '1.2rem',
							},
						},
						strong: {
							color: 'var(--text-main)',
							fontWeight: theme('fontWeight.bold'),
							'@screen lg': {
								fontSize: '1.2rem',
							},
						},
						em: {
							color: 'var(--text-main)',
							fontStyle: 'italic',
							'@screen lg': {
								fontSize: '1.2rem',
							},
						},
						code: {
							color: 'var(--text-main)',
							backgroundColor: 'var(--color-tag)',
							borderRadius: theme('borderRadius.md'),
							paddingLeft: theme('spacing.2'),
							paddingRight: theme('spacing.2'),
							paddingTop: '2px',
							paddingBottom: '2px',
							fontSize: '0.8rem',
							'@screen lg': {
								fontSize: '0.9rem',
							},
						},
						ul: {
							color: 'var(--text-main)',
							listStyleType: 'disc',
							paddingLeft: theme('spacing.8'),
							marginTop: theme('spacing.2'),
							marginBottom: theme('spacing.2'),
							'@screen lg': {
								fontSize: '1.2rem',
							},
						},
						ol: {
							color: 'var(--text-main)',
							listStyleType: 'decimal',
							paddingLeft: theme('spacing.8'),
							marginTop: theme('spacing.2'),
							marginBottom: theme('spacing.2'),
							'@screen lg': {
								fontSize: '1.2rem',
							},
						},
						li: {
							color: 'var(--text-main)',
							fontSize: theme('fontSize.base')[0],
							marginTop: theme('spacing.2'),
							marginBottom: theme('spacing.2'),
							lineHeight: theme('lineHeight.relaxed'),
							'@screen lg': {
								fontSize: '1.2rem',
							},
						},
						hr: {
							borderColor: 'var(--color-border)',
							marginTop: theme('spacing.8'),
							marginBottom: theme('spacing.8'),
							borderWidth: '0',
							height: '1px',
							backgroundColor: 'var(--color-border)',
						},
						img: {
							borderRadius: theme('borderRadius.DEFAULT'),
							maxWidth: '100%',
							height: 'auto',
							marginTop: theme('spacing.4'),
							marginBottom: theme('spacing.4'),
						},
						video: {
							width: '100%',
							borderRadius: theme('borderRadius.DEFAULT'),
							marginTop: theme('spacing.4'),
							marginBottom: theme('spacing.4'),
						},
						table: {
							width: '100%',
							borderCollapse: 'collapse',
							borderColor: 'var(--color-border)',
							borderWidth: '1px',
							marginTop: theme('spacing.8'),
							marginBottom: theme('spacing.8'),
							fontSize: '0.9rem',
							'@screen lg': {
								fontSize: '1rem',
							},
						},
						th: {
							color: 'var(--text-main)',
							backgroundColor: 'var(--color-tag)',
							fontWeight: theme('fontWeight.semibold'),
							paddingLeft: theme('spacing.4'),
							paddingRight: theme('spacing.4'),
							paddingTop: theme('spacing.2'),
							paddingBottom: theme('spacing.2'),
							borderWidth: '1px',
							borderColor: 'var(--color-border)',
						},
						td: {
							color: 'var(--text-main)',
							backgroundColor: 'var(--color-surface)',
							paddingLeft: theme('spacing.4'),
							paddingRight: theme('spacing.4'),
							paddingTop: theme('spacing.2'),
							paddingBottom: theme('spacing.2'),
							borderWidth: '1px',
							borderColor: 'var(--color-border)',
						},
						blockquote: {
							color: 'var(--text-muted)',
							borderLeftColor: 'var(--color-border)',
							fontStyle: 'italic',
						},
						pre: {
							backgroundColor: 'var(--color-surface)',
							color: 'var(--text-main)',
							borderRadius: theme('borderRadius.md'),
						},
						'pre code': {
							backgroundColor: 'transparent',
							padding: '0',
						},
					},
				},
				invert: {
					css: {
						color: 'var(--text-main)',
						a: { color: 'var(--color-link)' },
						code: { backgroundColor: 'var(--color-tag)' },
					},
				},
			}),
		},
	},
	plugins: [
		require('@tailwindcss/typography'),
	],
}